global:
 resolve_timeout: 1m

route:
 receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: received_email
    from: sent_email
    smarthost: smtp.gmail.com:587
    auth_username: sent_email
    auth_identity: sent_email
    auth_password: pass_sent_email_app
    send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
