version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}
    influxdb-volume: {}

networks:
  grafana-network:
  prometheus-network:
  zabbix-network:
  influxdb-network:

services:
#----------GRAGANA DASHBOARD-------------------------------------------------
  grafana:
    image: grafana/grafana
    container_name: Grafana
    depends_on:
      - prometheus
      - zabbix-server
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
#      - ./grafana_data/provisioning/:/etc/grafana/provisioning/
    environment: 
      GF_INSTALL_PLUGINS:  "alexanderzobnin-zabbix-app,\
                            grafana-influxdb-08-datasource,\
                            grafana-kairosdb-datasource,\
                            grafana-piechart-panel,\
                            grafana-simple-json-datasource,\
                            grafana-worldmap-panel,\
                            grafana-clock-panel"    
#      GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER
#      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
    networks:
      - prometheus-network
      - grafana-network
      - zabbix-network 
      - influxdb-network     
    restart: always

#----------PROMETHEUS SERVICES------------------------------------------------- 
# Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server   
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
      - pushgateway:pushgateway
    depends_on:
      - cadvisor
      - pushgateway
    networks:
      - prometheus-network
    restart: always

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - prometheus-network
    restart: always

# alert manager
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - prometheus-network
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

# Cadvisor
  cadvisor:
    image: google/cadvisor
    container_name: Cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - prometheus-network
    restart: always

# push gateway
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - prometheus-network


#--------ZABBIX SERVICES--------------------------------------
# mysql
  mysql:
    container_name: mysql
    image: mysql:5.7
    networks:
      - zabbix-network
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - './zabbix/mysql:/var/lib/data'
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASS
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASS

# zabbix-server
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.4-latest
    networks:
      - zabbix-network
    links:
      - mysql
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASS
    depends_on:
      - mysql

# zabbix-frontend
  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.4-latest
    networks:
      - zabbix-network
    links:
      - mysql
    restart: always
    ports:
      - '8081:8080'
      - '8443:8443'
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASS
    depends_on:
      - mysql

# zabbix-agent
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent:latest
    user: root
    networks:
      - zabbix-network
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - ./zabbix-agent/var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=zabbix-server

#--------INFLUXDB SERVICES--------------------------------------
# influxDB
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    restart: always
    hostname: influxdb
    ports:
      - 8086:8086
      - 8089:8089/udp
    networks:
      - influxdb-network
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      INFLUXDB_DB: $INFLUX_DB
      INFLUXDB_USER: $INFLUXDB_USER
      INFLUXDB_USER_PASSWORD: $INFLUXDB_USER_PASSWORD


  # telegraf:
  #   image: telegraf:latest
  #   container_name: telegraf
  #   depends_on:
  #     - influxdb
  #   restart: always
  #   networks:
  #     - influxdb-network
  #   ports:
  #     - 8092:8092
  #     - 8094:8094
  #     - 8125:8125
  #   environment:
  #     - HOST_PROC=/host/proc
  #     - HOST_SYS=/host/sys
  #     - HOST_ETC=/host/etc
  #   links:
  #     - influxdb
  #   tty: true
  #   volumes:
  #     - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf