version: '3.5'

networks:
  zbx_net:
  grafana-network:
  prometheus-network:
#  influxdb-network:

volumes:
    prometheus_data:
    grafana_data:
    influxdb-volume:


services:
#----------GRAGANA DASHBOARD-------------------------------------------------
  grafana:
    image: grafana/grafana
    container_name: Grafana
    depends_on:
      - prometheus
      - zabbix-server-mysql
#      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
#      - ./grafana_data/provisioning/:/etc/grafana/provisioning/
    environment: 
      GF_INSTALL_PLUGINS:  "alexanderzobnin-zabbix-app,\
                            grafana-influxdb-08-datasource,\
                            grafana-kairosdb-datasource,\
                            grafana-piechart-panel,\
                            grafana-simple-json-datasource,\
                            grafana-worldmap-panel,\
                            grafana-clock-panel"    
#      GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER
#      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD
    networks:
      - prometheus-network
      - grafana-network
      - zbx_net 
#      - influxdb-network     
    restart: always

#----------PROMETHEUS SERVICES------------------------------------------------- 
# Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server   
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
      - pushgateway:pushgateway
    depends_on:
      - cadvisor
      - pushgateway
    networks:
      - prometheus-network
    restart: always

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - prometheus-network
    restart: always

# alert manager
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - prometheus-network
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

# Cadvisor
  cadvisor:
    image: google/cadvisor
    container_name: Cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - prometheus-network
    restart: always

# push gateway
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - prometheus-network


#--------INFLUXDB SERVICES--------------------------------------
# # influxDB
#   influxdb:
#     image: influxdb:1.8.10
#     container_name: influxdb
#     restart: always
#     hostname: influxdb
#     ports:
#       - 8086:8086
#       - 8089:8089/udp
#     networks:
#       - influxdb-network
#     volumes:
#       - influxdb-volume:/var/lib/influxdb
#     environment:
#       INFLUXDB_DB: $INFLUX_DB
#       INFLUXDB_USER: $INFLUXDB_USER
#       INFLUXDB_USER_PASSWORD: $INFLUXDB_USER_PASSWORD


  # telegraf:
  #   image: telegraf:latest
  #   container_name: telegraf
  #   depends_on:
  #     - influxdb
  #   restart: always
  #   networks:
  #     - influxdb-network
  #   ports:
  #     - 8092:8092
  #     - 8094:8094
  #     - 8125:8125
  #   environment:
  #     - HOST_PROC=/host/proc
  #     - HOST_SYS=/host/sys
  #     - HOST_ETC=/host/etc
  #   links:
  #     - influxdb
  #   tty: true
  #   volumes:
  #     - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf



 #--------mysql-server--------------------------------------
  mysql-server:
    image: mysql:8.0
    networks:
    - zbx_net
    ports:
      - '3306:3306'
    command:
    - mysqld
    - --character-set-server=utf8
    - --collation-server=utf8_bin
    - --default-authentication-plugin=mysql_native_password
    environment:
    - MYSQL_USER=$MYSQL_USER
    - MYSQL_DATABASE=$MYSQL_DB
    - MYSQL_PASSWORD=$MYSQL_PASS
    - MYSQL_ROOT_PASSWORD=$MYSQL_PASS
    - ZBX_JAVAGATEWAY=zabbix-java-gateway
    volumes:
    - /zabbix-mysql:/var/lib/mysql:rw
    security_opt:
     - seccomp:unconfined
 #--------zabbix-server-mysql--------------------------------------
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:alpine-latest
    networks:
    - zbx_net
    ports:
    - 10051:10051
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro 
    - /zabbix-data/alertscripts:/usr/lib/zabbix/alertscripts:ro
    - /zabbix-data/externalscripts:/usr/lib/zabbix/externalscripts:ro
    - /zabbix-data/export:/var/lib/zabbix/export:rw
    - /zabbix-data/modules:/var/lib/zabbix/modules:ro
    - /zabbix-data/enc:/var/lib/zabbix/enc:ro
    - /zabbix-data/ssh_keys:/var/lib/zabbix/ssh_keys:ro
    - /zabbix-data/mibs:/var/lib/zabbix/mibs:ro
    - /zabbix-data/snmptraps:/var/lib/zabbix/snmptraps:rw
    environment:
    - DB_SERVER_HOST=mysql-server
    - MYSQL_USER=$MYSQL_USER
    - MYSQL_DATABASE=$MYSQL_DB
    - MYSQL_PASSWORD=$MYSQL_PASS
    - MYSQL_ROOT_PASSWORD=$MYSQL_PASS
    - ZBX_JAVAGATEWAY=zabbix-java-gateway

    depends_on:
    - mysql-server

#--------zabbix-server-mysql--------------------------------------
  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    networks:
    - zbx_net
    ports:
    - 8081:8080
    - 8443:8443
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - /zabbix-nginx/nginx:/etc/ssl/nginx:ro
    - /zabbix-nginx/modules/:/usr/share/zabbix/modules/:ro
    environment:
    - ZBX_SERVER_HOST=zabbix-server-mysql
    - DB_SERVER_HOST=mysql-server
    - MYSQL_USER=$MYSQL_USER
    - MYSQL_DATABASE=$MYSQL_DB
    - MYSQL_PASSWORD=$MYSQL_PASS
    - MYSQL_ROOT_PASSWORD=$MYSQL_PASS
    depends_on:
    - mysql-server
    - zabbix-server-mysql

#--------zabbix-java-gateway--------------------------------------
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:alpine-6.0-latest
    networks:
    - zbx_net
    ports:
    - 10052:10052
